server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_auth
    static_configs:
      - targets:
          - localhost
        labels:
          job: authlog
          host: vps-master
          __path__: /var/log/auth.log

  - job_name: cowrie_honeypot
    static_configs:
      - targets:
          - localhost
        labels:
          job: cowrie
          host: vps-master
          __path__: /cowrie-logs/cowrie.json
